# Generated by Django 4.2.2 on 2023-06-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento_data', models.DateTimeField(blank=True, null=True)),
                ('falecimento_data', models.DateTimeField(blank=True, null=True)),
                ('nascimento_local', models.CharField(blank=True, max_length=100, null=True)),
                ('falecimento_local', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
