# Generated by Django 4.2.2 on 2023-06-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0002_alter_memorias_falecimento_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorias',
            old_name='falecimento_data',
            new_name='data_de_falecimento',
        ),
        migrations.RenameField(
            model_name='memorias',
            old_name='nascimento_data',
            new_name='date_de_nascimento',
        ),
        migrations.RenameField(
            model_name='memorias',
            old_name='falecimento_local',
            new_name='local_de_falecimento',
        ),
        migrations.RenameField(
            model_name='memorias',
            old_name='nascimento_local',
            new_name='local_de_nascimento',
        ),
    ]
