# Generated by Django 4.2.2 on 2023-06-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0003_rename_falecimento_data_memorias_data_de_falecimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorias',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
