# Generated by Django 4.2.2 on 2023-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0004_rename_descricao_memorias_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorias',
            old_name='date_de_nascimento',
            new_name='data_de_nascimento',
        ),
        migrations.AddField(
            model_name='memorias',
            name='ano_de_falecimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorias',
            name='ano_de_nascimento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
