# Generated by Django 4.2.2 on 2023-06-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0005_rename_date_de_nascimento_memorias_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorias',
            name='ano_de_falecimento',
            field=models.IntegerField(blank=True, help_text='Preencher caso o dia exato de falecimento seja desconhecido', null=True),
        ),
        migrations.AlterField(
            model_name='memorias',
            name='ano_de_nascimento',
            field=models.IntegerField(blank=True, help_text='Preencher caso o dia exato de nascimento seja desconhecido', null=True),
        ),
    ]
