# Generated by Django 4.2.2 on 2023-07-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0006_alter_memorias_ano_de_falecimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorias',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
